<?php
/**
 * @author Hervé Guétin <www.linkedin.com/in/herveguetin>
 */

use Magento\Framework\View\Element\Template; ?>
<?php
/** @var Template $block */
?>
<script>
    document.addEventListener('zermatt:init', function () {
        Alpine.bind(document.querySelector('#search_mini_form'), () => ({
            'x-data': () => {
                return {
                    query: '',
                    init() {
                        Alpine.bind(this.$el.querySelector('#search'), () => ({
                            'x-model': 'query',
                            '@input.debounce': () => this.onInputChange()
                        }))
                    },
                    onInputChange() {
                        console.log(this.query)
                    }
                }
            }
        }))
    })
</script>
