<?php
/**
 * @author Hervé Guétin <www.linkedin.com/in/herveguetin>
 */ ?>
<?php
/** @var \Magento\Framework\View\Element\Template $block */
?>

<?php // The Alpine part ?>
<h2>Knockout / Alpine communication</h2>
<h4>Alpine</h4>
<div x-data="{}">
    <form action="#">
        <input @input.debounce="$dispatch('zermatt_example:alpine_input', $event.target.value)" type="text">
    </form>
</div>

<?php // The Knockout part ?>
<h4>Magento UI Component</h4>
<div data-bind="scope: 'zermatt_example_knockout'">
    <div data-bind="text: message()"></div>
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "zermatt_example_knockout": {
                        "component": "Maddlen_ZermattExamples/js/knockout"
                    }
                }
            }
        }
    }
</script>
