<?php
/**
 * @author Hervé Guétin <www.linkedin.com/in/herveguetin>
 */ ?>
<?php
/** @var \Magento\Framework\View\Element\Template $block */
?>
<?php $priceValue = 100 ?>
<div x-data="{
    price: <?= $priceValue ?>,
    discount: 10,
    get finalPrice() {
        return this.price - this.discount
    },
    formatPrice(...args) {
        return Zermatt.Money.formatPrice(...args)
    }
}">
    <h2>Price</h2>
    <div>Price was:
        <span x-text="formatPrice(price)"></span>
    </div>
    <div>Final price is:
        <span x-text="formatPrice(finalPrice)"></span>
    </div>
    <div>Final price as Euros:
        <span x-text="formatPrice(finalPrice, {currency: 'EUR'})"></span>
    </div>
    <div>Final price as Euros, formatted for France:
        <span x-text="formatPrice(finalPrice, {locale: 'fr_FR', currency: 'EUR'})"></span>
    </div>
</div>
