<?php
/**
 * @author Hervé Guétin <www.linkedin.com/in/herveguetin>
 */ ?>
<?php
/** @var \Magento\Framework\View\Element\Template $block */
?>
<?php $priceValue = 100 ?>
<div x-data="{
    price: <?= $priceValue ?>,
    discount: 10,
    get finalPrice() {
        return this.price - this.discount
    },
    formatPrice(price) {
        return Zermatt.Money.formatPrice(price)
    }
}">
    <h2>Price</h2>
    <div>Price was: <span x-text="formatPrice(price)"></span></div>
    <div>Final price is: <span x-text="formatPrice(finalPrice)"></span></div>
</div>
