<?php
/**
 * @author Hervé Guétin <www.linkedin.com/in/herveguetin>
 */ ?>
<?php
/** @var \Magento\Framework\View\Element\Template $block */
?>
<h4>Component "<?= $block->getData('name') ?>"</h4>
<?php if ($subPrefix = $block->getData('sub_prefix')): ?>
    <?php zermatt_component("Maddlen_ZermattExamples::components/{$subPrefix}-component.phtml", ['name' => $block->getData('name')]) ?>
<?php endif; ?>
