<?php
/**
 * @author Hervé Guétin <www.linkedin.com/in/herveguetin>
 */ ?>
<?php
/** @var \Magento\Framework\View\Element\Template $block */
?>
<label for="<?= $block->getId() ?>"><?= $block->getLabel() ?></label>
<input
    id="<?= $block->getId() ?>"
    name="<?= $block->getName() ?>"
    x-model="form.<?= $block->getName() ?>"
    @change="validate('<?= $block->getName() ?>')"
/>
<?php if ($block->getValidate()): ?>
    <?php zermatt_partial('Maddlen_ZermattExamples::partials/form/error.phtml', ['field' => $block->getName()]) ?>
<?php endif  ?>
